# this config for test env, lol
api_key: AGRYeKWvMcOSsg6STAhN7Ft9RRj76wpVcTPsaOcEgB1MfugMTfdGFIIU8OxyyhjG
secret_key: 4A7dPmquWzeJ1teAnTxSNQBjvB2cqAaSMNN4mywgp5FP5k4zWBbosh1mS8kfkQok
is_testnet: true
bock: 10000
interval_check_tp: 10
interval_check_buy: 3
price_will_took_profit: 406.18