# this config for test env, lol
api_key: AGRYeKWvMcOSsg6STAhN7Ft9RRj76wpVcTPsaOcEgB1MfugMTfdGFIIU8OxyyhjG
secret_key: 4A7dPmquWzeJ1teAnTxSNQBjvB2cqAaSMNN4mywgp5FP5k4zWBbosh1mS8kfkQok
is_testnet: true
block: 86400
interval_check_tp: 300
interval_check_buy: 1800
price_will_took_profit: 800
amount_usdt_each_block: '11'
mysql_dsn: root:12345678@tcp(localhost:3306)/dca_bot?parseTime=true
postgres_dns: 'host=localhost user=postgres password=example dbname=dca_bot port=5432 sslmode=disable TimeZone=Asia/Shanghai'
port: '80'
database_url: test
noti:
  url: "test"
  chat_id: "test"